security:
  jwt:
    secret: secret
    expiration-date: 36000000
    header-string: Authorization
    token-prefix: "Bearer "
    sign-up-url: /user/sign-up
    access-token-cookie-name: accessCookie
    refresh-token-cookie-name: refreshCookie
