security:
  jwt:
    secret: secret
    access-token-expiration-date: 3600000
    refresh-token-expiration-date: 7776000000
    header-string: Authorization
    token-prefix: "Bearer "
    sign-up-url: /user/sign-up
    access-token-cookie-name: accessCookie
    refresh-token-cookie-name: refreshCookie
