security:
  jwt:
    secret: ${JWT_SECRET_KEY}
    expiration-date: ${JWT_EXPIRATION_DATE}
    header-string: Authorization
    token-prefix: "Bearer "
    sign-up-url: /user/sign-up
    access-token-cookie-name: ${ACCESS_TOKEN_COOKIE_NAME}
    refresh-token-cookie-name: ${REFRESH_TOKEN_COOKIE_NAME}

spring:
  data:
    mongodb:
      uri: ${MONGO_URI}