security:
  jwt:
    secret: secret
    expiration-date: 3600000
    header-string: Authorization
    token-prefix: "Bearer "
    sign-up-url: /user/sign-up

spring:
  devtools:
    livereload:
      enabled: false