security:
  jwt:
    secret: ${TOKEN_SECRET_KEY}
    access-token-expiration-date: ${ACCESS_TOKEN_EXPIRATION_DATE}
    refresh-token-expiration-date: ${REFRESH_TOKEN_EXPIRATION_DATE}
    sign-up-url: /user/sign-up
    access-token-cookie-name: accessCookie
    refresh-token-cookie-name: refreshCookie
  cors:
    allowed-origins: https://cobudget.stasiak.xyz
    allowed-methods: GET, POST, PUT, PATCH, DELETE, ORIGIN, OPTIONS
    allowed-headers: Origin, Content-Type, Accept, Authorization, Cache-Control, Set-Cookie
    max-age: 3600

spring:
  data:
    mongodb:
      uri: ${MONGO_URI}