# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Run unit tests with Maven

on:
  push:
    branches: [ main ]

defaults:
  run:
    working-directory: ./backend

jobs:

  check:
    name: Check if backend files changed
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: check modified files
        id: check_files
        run: |
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD

          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file
          do
            echo $file
            if [[ $file != backend/* ]]; then
              echo "This modified file is not under the 'backend' folder."
              echo "::set-output name=cancel_job::true"
              break
            else
              echo "::set-output name=cancel_job::false"
            fi
          done < files.txt
      - name: cancel flow
        if: steps.check_files.outputs.cancel_job == 'true'
        uses: andymckay/cancel-action@0.2

  build_and_test:

    name: Java - unit tests
    runs-on: ubuntu-latest
    needs: check

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: ./mvnw -B test --file pom.xml
